apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retail-support-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: retail-support.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: retail-support-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: retail-support-frontend
                port:
                  number: 80
